"""Synthetic hourly weather for tests and the in-app demo.

These are NOT CIBSE data: a smooth seasonal and diurnal cycle with noise, plus
optional warm spells, shaped roughly like a southern-English climate.
"""

from __future__ import annotations

from dataclasses import dataclass

import numpy as np
import pandas as pd

from .model import NOMINAL_YEAR, WeatherSeries


@dataclass
class WarmSpell:
    peak_day: int  # day of year of the peak
    duration_days: int
    amplitude: float  # extra degC at the peak


def synthetic_year(
    mean: float = 11.5,
    seasonal_amplitude: float = 7.0,
    diurnal_amplitude: float = 4.0,
    spells: list[WarmSpell] | None = None,
    warming: float = 0.0,
    seed: int = 0,
    year: int = NOMINAL_YEAR,
) -> pd.Series:
    """Hourly dry-bulb for one non-leap year."""
    rng = np.random.default_rng(seed)
    idx = pd.date_range(f"{year}-01-01", periods=8760, freq="h")
    doy = idx.dayofyear.to_numpy() + idx.hour.to_numpy() / 24
    seasonal = mean + warming - seasonal_amplitude * np.cos(2 * np.pi * (doy - 20) / 365)
    # Diurnal swing is larger in summer.
    swing = diurnal_amplitude * (1 + 0.4 * np.sin(2 * np.pi * (doy - 80) / 365))
    diurnal = -swing * np.cos(2 * np.pi * (idx.hour.to_numpy() - 3) / 24)
    # Day-to-day weather: smoothed red noise.
    daily_noise = np.convolve(rng.normal(0, 2.2, 400), np.ones(4) / 4, mode="same")[:365]
    noise = np.repeat(daily_noise, 24) + rng.normal(0, 0.4, 8760)
    extra = np.zeros(8760)
    for s in spells or []:
        width = s.duration_days / 2
        shape = np.clip(1 - ((doy - s.peak_day) / max(width, 0.5)) ** 2, 0, None)
        extra += s.amplitude * shape * (1 + 0.3 * np.clip(-np.cos(2 * np.pi * (idx.hour.to_numpy() - 3) / 24), 0, None))
    return pd.Series(seasonal + diurnal + noise + extra, index=idx, name="dry_bulb")


def synthetic_series(name: str, typical: bool = True, **kwargs) -> WeatherSeries:
    temps = synthetic_year(**kwargs)
    return WeatherSeries(name, temps.to_frame(), "synthetic", {"typical_year": typical})


def to_epw(series: WeatherSeries, site: str = "Synthetic", year: int | None = None) -> str:
    """Minimal EPW text (only the columns this app reads are meaningful)."""
    header = [
        f"LOCATION,{site},,GBR,Synthetic,000000,51.48,-0.45,0.0,25.0",
        "DESIGN CONDITIONS,0",
        "TYPICAL/EXTREME PERIODS,0",
        "GROUND TEMPERATURES,0",
        "HOLIDAYS/DAYLIGHT SAVINGS,No,0,0,0",
        "COMMENTS 1,Synthetic data generated by summers_dsy - not CIBSE data",
        "COMMENTS 2,",
        "DATA PERIODS,1,1,Data,Sunday, 1/ 1,12/31",
    ]
    rows = []
    for ts, t in series.dry_bulb.items():
        y = year or ts.year
        rows.append(f"{y},{ts.month},{ts.day},{ts.hour + 1},60,*,{t:.1f},{t - 6:.1f},70,101325" + ",0" * 25)
    return "\n".join(header + rows) + "\n"


def demo_library() -> dict[str, tuple[WeatherSeries, dict]]:
    """A small synthetic 'DSY set' for trying the app without licensed files."""
    loc = "Demo (synthetic)"
    sets = {}
    scenarios = [
        ("Baseline", None, None, 0.0),
        ("2020s", "High", 50, 0.9),
        ("2050s", "Medium", 50, 1.6),
        ("2050s", "High", 50, 2.1),
        ("2080s", "High", 50, 3.6),
    ]
    kinds = {
        "TRY": [WarmSpell(200, 4, 3.0)],
        "DSY1": [WarmSpell(190, 6, 5.0), WarmSpell(225, 4, 4.0)],
        "DSY2": [WarmSpell(215, 5, 9.5)],
        "DSY3": [WarmSpell(200, 20, 6.0)],
    }
    for s_i, (period, emissions, pct, warming) in enumerate(scenarios):
        for k_i, (kind, spells) in enumerate(kinds.items()):
            if kind == "TRY" and period != "Baseline":
                continue
            meta = {"location": loc, "kind": kind, "period": period, "emissions": emissions, "percentile": pct}
            series = synthetic_series(f"{kind} {period}", spells=spells, warming=warming, seed=10 + k_i)
            sets[f"Demo_{kind}_{period}{emissions or ''}{pct or ''}.epw"] = (series, meta)
    return sets
